repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
    -   id: ruff
        args: [--fix]
        types_or: [python, pyi]
    -   id: ruff-format
        types_or: [python, pyi]

# TODO: Enable mypy after fixing type annotations
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.11.2
#     hooks:
#     -   id: mypy
#         additional_dependencies: [types-requests]
#         exclude: ^(tests/|docs/)
